config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/edit' => 'devise/sessions#edit'
  end
  get 'static_pages/help'
  get 'static_pages/contact'
  resources :users
  resources :meetings_lists do
    resources :meetings_items do
      member do
        patch :complete
      end
    end
  end
  root 'static_pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meetings_item.rb
# Meetings items class
class MeetingsItem < ApplicationRecord
  validates :date, :reason, :amount, presence: true

  belongs_to :meetings_list
  monetize :amount_cents, allow_nil: true, default: nil
  def completed?
    !completed_at.blank?
  end
end

app/models/meetings_list.rb
# frozen_string_literal: true

class MeetingsList < ApplicationRecord
  validates_presence_of :title, :responsible
  has_many :meetings_items, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  enum role: %i[user editor admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role = 0
  end

  def self.from_omniauth(provider_data)
    where(provider: provider_data.provider,
          uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private

  def user_not_authorized
    flash[:alert] = 'Benutzer ist nicht Autorisiert'
    redirect_to request.referrer || root_path
  end
end

app/controllers/meetings_items_controller.rb
# frozen_string_literal: true

class MeetingsItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting_list
  before_action :set_meetings_item, except: %i[create]

  def create
    @meetings_item = @meetings_list.meetings_items.create(meeting_item_params)
    if @meetings_item.valid?
      @meetings_item.save
      redirect_to @meetings_list, notice: 'Neuer Eintrag hinzugefügt'
    else
      render :new
    end
  end

  def new
    @meetings_item = MeetingsItem.new
  end

  def destroy
    # puts @meetings_item
    authorize @meetings_item
    # flash[:notice] = ('Item erfolgreich vernichtet.' if @meetings_item.destroy)
    # redirect_to @meetings_list
    @meetings_item.destroy
    respond_to do |format|
      format.html do
        redirect_to @meetings_list, notice: 'Item erfolgreich vernichtet.'
      end
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @meetings_item.update(meeting_item_params)
        format.html do
          redirect_to @meetings_list, notice: 'Item erfolgreich aktualisiert'
        end
        format.json { render :show, status: :ok, location: @meetings_list }
      else
        format.html { render :edit }
        format.json { render json: @meetings_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def complete
    @meetings_item.update_attribute(:completed_at, Time.now)
    redirect_to @meetings_list, notice: 'Aufgabe erledigt'
  end

  private

  def set_meeting_list
    # puts params[:meetings_list_id]
    @meetings_list = MeetingsList.find(params[:meetings_list_id])
  end

  def set_meetings_item
    # puts params[:id]
    @meetings_item = @meetings_list.meetings_items.find_by(id: params[:id])
  end

  def meeting_item_params
    params[:meetings_item].permit(:date, :reason, :amount)
  end
end

app/controllers/meetings_lists_controller.rb
class MeetingsListsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_meetings_list, only: %i[show edit update destroy]

  # GET /meetings_lists
  # GET /meetings_lists.json
  def index
    @meetings_lists = MeetingsList.all
  end

  # GET /meetings_lists/1
  # GET /meetings_lists/1.json
  def show
    @show_total = Money.new @meetings_list.meetings_items.sum(:amount_cents)
  end

  # GET /meetings_lists/new
  def new
    @meetings_list = MeetingsList.new
    authorize @meetings_list
  end

  # GET /meetings_lists/1/edit
  def edit; end

  # POST /meetings_lists
  # POST /meetings_lists.json
  def create
    @meetings_list = MeetingsList.new(meetings_list_params)

    respond_to do |format|
      if @meetings_list.save
        format.html { redirect_to @meetings_list, notice: 'Die Meeting-Liste wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @meetings_list }
      else
        format.html { render :new }
        format.json { render json: @meetings_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings_lists/1
  # PATCH/PUT /meetings_lists/1.json
  def update
    respond_to do |format|
      if @meetings_list.update(meetings_list_params)
        format.html do
          redirect_to @meetings_list,
                      notice: 'Die Meeting-Liste wurde erfolgreich aktualisiert.'
        end
        format.json { render :show, status: :ok, location: @meetings_list }
      else
        format.html { render :edit }
        format.json { render json: @meetings_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings_lists/1
  # DELETE /meetings_lists/1.json
  def destroy
    @meetings_list.destroy
    authorize(@meetings_list.destroy)
    respond_to do |format|
      format.html do
        redirect_to root_url,
                    notice: 'Liste erfolgreich vernichtet.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meetings_list
    @meetings_list = MeetingsList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meetings_list_params
    params.require(:meetings_list).permit(:title, :responsible)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def help; end

  def contact; end

  def home; end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, notice: 'Nutzer Gelöscht'
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update(secure_params)

      redirect_to users_path,
                  notice: 'Benutzer erfolgreich aktualisiert'
      # else
      #  flash[:error] = 'nicht in der Lage zu aktualisieren'
      # render users_path
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/input_helper.rb
module InputHelper
end

app/helpers/meetings_items_helper.rb
# frozen_string_literal: true

module MeetingsItemsHelper
end

app/helpers/meetings_lists_helper.rb
# frozen_string_literal: true

module MeetingsListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Spende App | 
      = yield(:title)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link[href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,900&family=Oswald:wght@300;500&display=swap" rel="stylesheet" type="text/css"]
    link[href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"]
    meta name="viewport" content="width=device-width, initial-scale=1.0"/
    / Global config for input masking in Cleave library
    javascript:
        window.__AMOUNT_INPUT_MASK__ = {
        prefix: "#{raw Money.default_currency.symbol} ",
        numeral: true,
        numeralThousandsGroupStyle: 'thousand',
        rawValueTrimPrefix: true,
        numeralDecimalMark: ',',
        delimiter: '.'
        };
  body
    - if notice
      p.alert.alert-success
        = notice
    - if alert
      p.alert.alert-danger
        = alert
  = render 'devise/nav_partial/nav'
  .container
    = yield

app/views/meetings_items/_edit_form.html.slim
- provide(:title, "#{@meetings_list.title}")
= form_with(model: [ @meetings_list, @meetings_item ], local: true, method: :put) do |form|
  = render 'eintrag_errors'
  .date_wrapper
    = form.label :date, "Datum:"
    = form.text_field :date, data: {controller: "flatpickr", 
                                 flatpickr_alt_format: t("date.formats.long"),
                                 flatpickr_alt_input: true,
                                 }
  .currency-input
    = form.label :amount, "Betrag:"
    = form.text_field :amount, class: "currency-input-mask"
  .reason-input
    = form.label :reason, "Grund:"
    = form.text_field :reason
  .actions
    = form.submit value: "Neuer Eintrag"

app/views/meetings_items/_eintrag_errors.html.slim
- if @meetings_item.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      count: @meetings_item.errors.count,
      resource: @meetings_item.class.model_name.human.downcase)
    ul
      - @meetings_item.errors.full_messages.each do |message|
        li
          = message

app/views/meetings_items/_form.html.slim
- provide(:title, "#{@meetings_list.title}")
= form_with(model: [ @meetings_list, MeetingsItem.new ], local: true) do |form|
  = render 'eintrag_errors'
  .date_wrapper
    = form.label :date, "Datum:"
    = form.text_field :date, data: {controller: "flatpickr", 
                                 flatpickr_alt_format: t("date.formats.long"),
                                 flatpickr_alt_input: true,
                                 },
                                 placeholder: "Wähle das Datum aus"
  .currency-input
    = form.label :amount, "Betrag:"
    = form.text_field :amount, class: "currency-input-mask"
  .reason-input
    = form.label :reason, "Grund:"
    = form.text_field :reason, placeholder: "Gebe bitte den Verwendungszweck an"
  .actions
    = form.submit value: "Neuer Eintrag"

  

app/views/meetings_items/_meetings_item.html.slim
.row.clearfix
  - if meetings_item.completed?
    .complete
      = link_to complete_meetings_list_meetings_item_path(@meetings_list, meetings_item.id), method: :patch do
        i.fa.fa-check[style="opacity: 0,4;"]
    .meetings_item
      p[style="opacity: 0,4;"]
        strike
          = meetings_item.date
    .meetings_reason
      p[style="opacity: 0,4;"]
        strike
          = meetings_item.reason
    .meetings_amount
      p[style="opacity: 0,4;"]
        strike
          = humanized_money_with_symbol meetings_item.amount
    .trash
      = link_to meetings_list_meetings_item_path(@meetings_list, meetings_item),method: :delete, data: { confirm: "Bist du sicher diesen Eintrag zu löschen?" } do
        i.fa.fa-trash
  - else
    .complete
      = link_to complete_meetings_list_meetings_item_path(@meetings_list, meetings_item.id), method: :patch do
        i.fa.fa-check
    .meetings_item
      p
        = meetings_item.date
    .meetings_reason
      p
        = meetings_item.reason
    .meetings_amount
      p
        = humanized_money_with_symbol meetings_item.amount
    .trash
      = link_to meetings_list_meetings_item_path(@meetings_list, meetings_item),method: :delete, data: { confirm: "Bist du sicher?" } do
        i.fa.fa-trash
    .edit
      = link_to edit_meetings_list_meetings_item_path(@meetings_list, meetings_item.id), method: :get do
        i.fa.fa-edit

app/views/meetings_items/edit.html.slim
h1.meetings_list_title
  | Bearbeiten Eintrag
#meetings_items_wrapper
  #form
    = render 'edit_form'
  .links
    = link_to 'Cancel', @meetings_list

app/views/meetings_items/new.html.slim
h1.meetings_list_title
  | Neuer Eintrag
#meetings_items_wrapper
  #form
    = render  'form'
  .links
    = link_to 'Cancel', @meetings_list

app/views/meetings_lists/_form.html.slim
- provide(:title, "#{@meetings_list.title}")
= form_with(model: meetings_list, local: true) do |form|
  - if meetings_list.errors.any?
    #error_explanation
      h2
        = pluralize(meetings_list.errors.count, "error")
        |  prohibited this meetings_list from being saved:
      ul
        - meetings_list.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label "titel"
    = form.text_field :title
  .field
    = form.label "verantwortlich"
    = form.text_field :responsible
  .actions
    = form.submit value: "Erstellen"

app/views/meetings_lists/edit.html.slim
h1.meetings_list_title
  | Edit Meetings List
.forms
  = render 'form', meetings_list: @meetings_list
.links
  = link_to 'Cancel', meetings_lists_path

app/views/meetings_lists/index.html.slim
= provide(:title, "Index")
- @meetings_lists.each do |meetings_list|
  .index_row.clearfix
    h2.meetings_list_title
      = link_to meetings_list.title, meetings_list
    p.meetings_list_sub_title
      = meetings_list.responsible
.initial_button
  = link_to  "Neue Liste", new_meetings_list_path

app/views/meetings_lists/new.html.slim
- provide(:title, "Neue Meeting")
h1.meetings_list_title
  | Neue Meeting
.forms
  = render 'form', meetings_list: @meetings_list
.links
  = link_to 'Back', meetings_lists_path

app/views/meetings_lists/show.html.slim
- provide(:title, "#{@meetings_list.title}")
h2.meetings_list_title
  = @meetings_list.title
p.meetings_list_sub_title
  = @meetings_list.responsible
.total
  = "total: #{ humanized_money_with_symbol @show_total }"
#meetings_items_wrapper
  .items_container
    = render  @meetings_list.meetings_items
.links
  - if policy(@meetings_list).show?
    = link_to "New entry", new_meetings_list_meetings_item_path(@meetings_list)
    |  | 
    = link_to 'Edit', edit_meetings_list_path(@meetings_list)
    |  | 
    = link_to "Delete", meetings_list_path(@meetings_list), method: :delete, data: { confirm: "Bist du sicher?" }
    |  | 
    = link_to 'Back', meetings_lists_path

app/views/static_pages/contact.html.slim
- provide(:title, "Kontakt")
h1.meetings_list_title
 | Hallo!
#contact_style
  .contact_box
    p 
      | Hast du Vorschläge oder Kommentare?
    p
      | dann sende eine 
      a> href='mailto:rafedraper@gmail.com' e-mail
      | oder 
      a> href='https://twitter.com/Rafe_Draper' dm auf twitter
  .back_link 
    = link_to fa_icon('chevron-circle-left', type: :solid, text: "Zurück nach Home"), root_path

app/views/static_pages/help.html.slim
- provide(:title, "Hilfe")
h1.meetings_list_title
 | Wie benutzen die App:
.static_container
  .inner_text
    p
      h3 Erstellen einer neuen Liste:
      p
        | Klicke den Button "Neue Liste" an und gebe den Namen und den Verantwortlichen ein.
      i
        | * Funktion nur für Administratoren verfügbar.
      h3 Erstellen eines neuen Eintrags:

      p 
        | Sobald eine Liste von einem Administrator erstellt wurde, sind neue Einträge erlaubt,
        | damit die Einnahmen und Ausgaben verfolgt werden können. Um einen neuen Eintrag zu erstellen, 
        | klicke den Button "Neuer Eintrag" unten auf der Liste an und fülle dann alle erforderlichen 
        | Felder aus: (Datum, Betrag, Grund). Speichere die Eingabe und diese wird auf der ersten Seite 
        | der Liste verfügbar sein.

      i
        | * Funktion nur für Redakteure und Administratoren verfügbar.
      h3 Für den Rest der Benutzer:
      p 
       | Jeder registrierte Benutzer der App wird alle verfügbaren Einträge sehen können, 
       | kann aber keine neuen Einträge bearbeiten oder hinzufügen. Bitte kontaktier den  
       | Administrator für weitere Berechtigungen.
      .back_link
        = link_to fa_icon('chevron-circle-left', type: :solid, text: "Zurück"), root_path
      

app/views/static_pages/home.html.slim
- provide(:title, 'Home')
.index_title
  p.top
    | Spende
    span Kollektor
  .initial_button#container_link_list
    = link_to fa_icon('list-ul', type: :solid, text: "Listen"),  meetings_lists_path

app/views/users/_user.html.slim
td
  = link_to user.email, user
td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    td
      = f.submit 'Change Role'
td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Bist du sicher?" }, :method => :delete, :class => 'button') unless user == current_user

app/views/users/index.html.slim
- provide(:title, "Nutzer Konsole")
h2.meetings_list_title
  | Nutzer Konsole
table.user_table
  tbody
    - @users.each do |user|
      tr
      = render user
.links 
  = link_to 'Züruck nach Listen', root_path

app/views/users/show.html.slim
h3 User
p 
  |Email: 
  = @user.email